name: Check roles

on:
  push:
  # pull_request:
  #   types: [opened, synchronize, reopened]
    branches:
      - main 

    # Trigger only when files within specific folders change!
    paths:
      - 'base/**'
      - '.github/workflows/check_roles.yml'

jobs:
  check-roles:
    name: Check newly assigned roles in (${{ matrix.folder }})
    runs-on: ubuntu-latest
    # Use a matrix strategy to run the job for each changed folder
  
    strategy:
      matrix:
        folder:
          - base
          # - sn-infrastructure
          # - test-extra-folder 
          # Add more folders as needed  
 
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
            fetch-depth: 2

      # step1: Check if there were changes in folder
      - name: Check for changes in folder
        id: changes
        run: |
            changes=$(git diff --name-only HEAD^ HEAD -- ${{ matrix.folder }})
            if [[ -n "$changes" ]]; then
                echo "changed=true" >> $GITHUB_OUTPUT
                echo "files=$changes" >> $GITHUB_OUTPUT
                
                # Print detailed changes
                echo "Detailed changes:"
                for file in $changes; do
                    echo "File: $file"
                    git diff HEAD^ HEAD -- "$file"
                done > detailed_changes.txt
            else
                echo "changed=false" >> $GITHUB_OUTPUT
                echo "files=" >> $GITHUB_OUTPUT
            fi

      # Show changes for debug
      - name: Show detailed changes
        if: steps.changes.outputs.changed == 'true'
        run: |
            cat detailed_changes.txt

      # step2.1: Check if forbidden roles were assigned in folders, if yes --> step3: Automatically reject this PR.
      - name: Check if forbidden roles were assigned in folder
        id: check-forbidden-roles
        run: |
          echo "Forbidden_DETECTED=false" >> $GITHUB_OUTPUT

          # Read the Forbidden roles from the JSON file
          Forbidden_ROLES=$(jq -r '.Forbidden[]' role_allow_list.json)

          # Loop through each role in the Not_Allowed list
          for ROLE in $Forbidden_ROLES; do
            if (git diff HEAD^ HEAD -- ${{ matrix.folder }} | grep -E "^\+.*${ROLE}") &&  !(git diff HEAD^ HEAD -- ${{ matrix.folder }} | grep -E "^\-.*${ROLE}") ; then
              echo "Detected forbidden role: ${ROLE}"
              echo "Forbidden_DETECTED=true" >> $GITHUB_OUTPUT
            else
              echo "Forbidden role ${ROLE} was not detected"
            fi
          done
      